### PR TITLE
Add support for passport v0.6.0

### LINKED ISSUE #71: Outdated for passport 0.6.0
The new 0.6.0 version of passport, changes some of the parameters of login()/logout(), so seems like some changes are needed for `graphql-passport` to be fully compatible.

Example: https://github.com/jaredhanson/passport/commit/17111d76972462eab90a1ea5dcd9211ceb93c7b0
And: https://github.com/jaredhanson/passport/commit/e69834e070662e8972e9eca07cbebf0338cfd226

### PR DESCRIPTION
**Pull request by 0xb4lamx**
* fix #71 
* upgrade subscriptions-transport-ws
* fix unsecure packages

### CODE REVIEW

**Comment by gforge** [comment]
Changes look good to me. @jkettmann - can you go ahead with merge and npm-publish?

**Comment by jastako** [comment]
I (and others) would love to see it compatible with latest passport@0.6.0. Any chance for a green light?

**Comment by ericbf** [comment]
@jkettmann you still around? Had a chance to look at this?

**Comment by ecker00** [comment]
I've also been wondering the same. But maybe implementing auth without this dependency is a better way? I'm surprised this isn't a more popular package on npm. What are the popular approaches/packages people are using as an alternative for auth?

**Comment by jkettmann** [comment]
Sorry, have been letting this package slip. Tbh I don't really have the time to maintain it atm. I'd be happy to transfer it if anyone's interested

**Comment by jkettmann** [comment]
The new version 0.6.5 should be published on npm in a bit

**Comment by ericbf** [comment]
> Sorry, have been letting this package slip. Tbh I don't really have the time to maintain it atm. I'd be happy to transfer it if anyone's interested

@jkettmann this is a pretty popular pattern in my projects, including some apps for clients of mine. I’d be happy to take this on.

**Pull request merged**
